spring:
  elasticsearch:
    rest:
      uris: http://175.178.113.56:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
  redis:
    host: 175.178.113.56
    database: 0
    port: 6379
    timeout: 50000
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #最大阻塞等待时间（负数表示无限制）
        max-idle: 8 #最大空闲连接数

server:
  port: 8080
